version: "3.7"
services:
  arm_gun:
    container_name: arm_gun
    image: webdevops/php-nginx:7.4
    volumes:
      - ./:/app
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_DATE_TIMEZONE: Asia/Bangkok
      PHP_MEMORY_LIMIT: 2048M
      PHP_MAX_EXECUTION_TIME: 300
      PHP_POST_MAX_SIZE: 2048M
      PHP_UPLOAD_MAX_FILESIZE: 2048M

  db:
    image: mariadb:10.4-bionic
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./database/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: building_site_db
    ports:
      - 3306:3306
